import {
  AccessCodeIdEnum,
  AccessCodeTypeIDEnum,
  AccessMethodIdEnum,
  Amenities,
  AmenityCategories,
  BedroomTypeItem,
  BedroomTypes,
  Channel,
  EmergencyContactType,
  FormBookingPlatform,
  FormInputsReservationSettings,
  FormMostImportant,
  JoinStatusItem,
  LabelNameItem,
  NameIdDescriptionItem,
  PhotoValidation,
  Policies,
  PropertyManagerItem,
  PropertySetting,
  PropertySettingItem,
  RateAutomationItem,
  RateGroupItem,
  RateSuggestionItem,
  SearchFilters,
  Subforms,
  SubscriptionTier,
  SuitabilityItem,
} from './types';
import { CancellationPolicy, NameIdItem } from '../types';

import { RateInsightLevelIdEnum, RatesSettingsWeekendPremiumId } from '../property/types';

const TAX = {
  REGION_NAME: '',
  IS_MANDATORY: false,
  IS_REGISTRATION_NUMBER_REQUIRED: false,
  NAME: '',
  ID: 0,
  RESORT_NAME: '',
  RATE: 0,
  COUNTRY_NAME: '',
  DESCRIPTION: '',
};

export const initialFormInputs = {
  ACCESS_TO_UNIT: {
    TYPES: [
      {
        NAME: '',
        ID: 0 as AccessCodeIdEnum,
      },
    ],
    METHODS: [
      {
        NAME: '',
        ID: 0 as AccessMethodIdEnum,
      },
    ],
    CODES: [
      {
        NAME: '',
        ID: 0 as AccessCodeTypeIDEnum,
      },
    ],
  },
  ADVANCED_BOOKING: [] as NameIdItem[],
  AMENITIES: {
    BATHROOM: { CATEGORY: '', LIST: [], TITLE: '' },
    BUILDING: { CATEGORY: '', LIST: [], TITLE: '' },
    ESSENTIAL: { CATEGORY: '', LIST: [], TITLE: '' },
    KITCHEN: { CATEGORY: '', LIST: [], TITLE: '' },
    LAUNDRY: { CATEGORY: '', LIST: [], TITLE: '' },
    PRIVATE: { CATEGORY: '', LIST: [], TITLE: '' },
    SAFETY: { CATEGORY: '', LIST: [], TITLE: '' },
  } as Amenities,
  AMENITY_CATEGORIES: {
    BATHROOM: [],
    BUILDING: [],
    ESSENTIAL: [],
    KITCHEN: [],
    PRIVATE: [],
    SAFETY: [],
  } as AmenityCategories,
  BEDROOM_TYPES: [{
    SORT_ORDER: 0,
    NAME: '',
    ID: 0,
    DESCRIPTION: '',
    IS_BEDROOM: '',
  }] as BedroomTypes[],
  BED_TYPES: [] as BedroomTypeItem[],
  CONTACT_EMAIL_NOTIFICATION_TYPES: [] as LabelNameItem[],
  DAMAGE_DEPOSIT_MODES: [] as NameIdItem[],
  DEFAULT_CHANNELS: [] as Channel[],
  EMERGENCY_CONTACT_TYPES: [] as EmergencyContactType[],
  JOIN_STATUSES: [] as JoinStatusItem[],
  MILESTONE_MESSAGES: {} as any,
  NON_RESIDENT: {
    MIN_OWNERS: 0,
    MAX_OWNERS: 0,
  },
  PARTNERS: {} as any,
  CLEANING_PROTOCOL_URL: '',
  PHOTO_VALIDATION: {
    MAX_SIZE_MB: 0,
    MIN_HEIGHT_PIXELS: 0,
    ACCEPTED_FILE_FORMATS: '',
    ACCEPTED_FILE_FORMATS_EXTENSION: '',
    ACCEPTED_MIME_FORMATS: '',
    LOGO_MAX_SIZE_KB: 0,
    LOGO_MAX_SIZE_MB: 0,
    MAX_NUMBER_PHOTOS: 0,
    MAX_SIZE_BYTES: 0,
    MIN_NUMBER_PHOTOS: 0,
  } as PhotoValidation,
  POLICIES: {
    ACCOUNT: [],
    CANCELLATION: [],
    GENERAL: [],
    GUEST_STAY: [],
    RESERVATION: [],
  } as Policies,
  POLICIES_CANCELLATION: [] as CancellationPolicy[],
  POLICIES_CANCELLATION_SPECIAL: [] as NameIdDescriptionItem[],
  POLICIES_MANDATORY: [] as NameIdItem[],
  PROPERTY_CATEGORIES: [] as NameIdItem[],
  PROPERTY_MANAGERS: [] as PropertyManagerItem[],
  PROPERTY_STYLES: [] as NameIdItem[],
  RATES_SETTINGS: {
    RATE_GROUP_ITEMS: [] as RateGroupItem[],
    AVAILABILITY_WINDOW: [] as RateAutomationItem[],
    PROPERTY_SETTINGS: [] as PropertySetting[],
    RATE_GROUP_TYPES: [] as PropertySettingItem[],
    WEEKEND_PREMIUMS: [] as PropertySettingItem[],
    LAST_ALLURA_EVENT: '',
    EXTEND_RATES_SCHEDULE_MONTHS: [] as number[],
    REPLACE_RATES_SCHEDULE_MONTHS: [] as number[],
    RATE_INSIGHTS: [{ ID: 0 as RateInsightLevelIdEnum, NAME: '' }],
  },
  RATES_SETTINGS_SUGGESTIONS: {
    DISCOUNT_GROUP: {
      FIVE_NIGHTS: 0,
      ID: 0,
      SEVEN_NIGHTS: 0,
      TEN_NIGHTS: 0,
    },
    WEEKEND_PREMIUM_SUGGESTION: {
      PERCENTAGE_AMOUNT: 0,
      DOLLAR_AMOUNT: 0,
      ID: 0 as RatesSettingsWeekendPremiumId,
    },
    LAST_DAY_OF_SUGGESTIONS: '',
    RATE_INSIGHTS_LEVEL_ID: 0,
  },
  RATES_SUGGESTIONS: [] as RateSuggestionItem[],
  RESERVATION_SETTINGS: {
    DEPOSIT_PERCENTAGES: [] as number[],
    BALANCE_DUE_DATES: [],
    BOOKING_GATEWAY_MODES: [],
  } as FormInputsReservationSettings,
  REST_API_SEARCH_MIN_DATE: '',
  SUBSCRIPTION_TIERS: [] as SubscriptionTier[],
  SETUP_QUESTIONS: { MOST_IMPORTANT: [] as FormMostImportant[], PLATFORMS: [] as FormBookingPlatform[] },
  SUBFORMS_OPTIONAL: [] as string[],
  SUBFORMS: { OPTIONAL: [] as Subforms[], REQUIRED: [] as Subforms[] },
  SUITABILITIES: [] as SuitabilityItem[],
  SURCHARGES: [] as NameIdDescriptionItem[],
  TAXES: [] as typeof TAX[],
  TAX_NUMBERS: [] as NameIdDescriptionItem[],
  EXTERNAL_CHANNELS: [] as Channel[],
  SEARCH_FILTERS: {
    SOURCE: [],
    FILTER_BY: [],
    STATUS: [],
  } as SearchFilters,
  UNBOOKABLE_NIGHTS_DATE_RANGE: [{
    VALUE: 0, 
    LABEL: ""
  }]
};
